import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { LayoutClient } from "@/app/LayoutClient";
import { Header } from "@/components/Header/Header";
import { SideBar } from "@/components/SideBar/SideBar";
import "react-indiana-drag-scroll/dist/style.css";
import "@/app/globals.css";
import "@/app/typography.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          plusJakartaSans.variable,
          "sm:grid sm:grid-cols-1 sm:grid-rows-1 sm:h-dvh sm:w-full",
          "md:grid-cols-[18.75rem_1fr]",
        )}
      >
        <LayoutClient>
          <SideBar />

          <div className="sm:grid sm:grid-cols-1 sm:grid-rows-[auto_1fr] sm:h-full sm:w-full">
            <Header />

            {children}
          </div>
        </LayoutClient>
      </body>
    </html>
  );
}
