import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { LayoutClient } from "@/app/LayoutClient";
import { Header } from "@/components/Header/Header";
import "@/app/globals.css";
import "@/app/typography.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.variable}>
        <LayoutClient>
          <Header />

          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
